CREATE TABLE CLIENTE
(
    ID       NUMBER(11) AUTO_INCREMENT,
    NOME     VARCHAR(50) NOT NULL,
    EMAIL    VARCHAR(80) NOT NULL,
    TELEFONE VARCHAR(20)  NOT NULL,
    CONSTRAINT CLIENTE_PK PRIMARY KEY (ID)
);