CREATE TABLE ORDEM_SERVICO
(
    ID               NUMBER(11) AUTO_INCREMENT,
    CLIENTE_ID       NUMBER(11)     NOT NULL,
    DESCRICAO        VARCHAR(255)   NOT NULL,
    PRECO            DECIMAL(10, 2) NOT NULL,
    STATUS           VARCHAR(20)    NOT NULL,
    DATA_ABERTURA    DATETIME       NOT NULL,
    DATA_FINALIZACAO DATETIME,
    CONSTRAINT ORDEM_SERVICO_PK PRIMARY KEY (ID),
    CONSTRAINT FK_ORDEM_SERVICO_CLIENTE FOREIGN KEY (CLIENTE_ID) REFERENCES CLIENTE (ID)
);