CREATE TABLE COMENTARIO
(
    ID               NUMBER(11) AUTO_INCREMENT,
    ORDEM_SERVICO_ID NUMBER(11)   NOT NULL,
    DESCRICAO        VARCHAR(255) NOT NULL,
    DATA_ENVIO       DATETIME     NOT NULL,
    CONSTRAINT COMENTARIO_PK PRIMARY KEY (ID),
    CONSTRAINT FK_COMENTARIO_ORDEM_SERVICO FOREIGN KEY (ORDEM_SERVICO_ID) REFERENCES ORDEM_SERVICO (ID)
);